CREATE TABLE "ExerciseSessions" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Complete"	INTEGER NOT NULL,
	"DateComplete"	INTEGER NOT NULL,
	"User"	TEXT NOT NULL,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "Exercises" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"IsTimeBased"	INTEGER NOT NULL,
	"ExerciseSessionID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "Sets" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Weight"	INTEGER NOT NULL,
	"RepsOrDuration"	INTEGER NOT NULL,
	"Done"	INTEGER NOT NULL,
	"ExerciseID"	INTEGER NOT NULL,
	"TimestampAdded"	INTEGER NOT NULL,
	"TimestampCompleted"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);